### ISSUE TITLE
Push Giving error 404

### ISSUE THREAD

**Issue by rashedsahaji** [oceanbit-dev/GitShark#47]
I have logged in with my git account, cloned one of my repo, made some edit, made it unstaged to staged. Committed all after that if hit push giving me an error of 404 not found

**Comment by crutchcorn** [comment]
Are you able to share the URL you used to clone the repo? (If you're not, can you at least tell me what service it's hosted on [GitLab, GitHub, Azure DevOps], and if the clone URL ends with `.git` or not?)

**Comment by rashedsahaji** [comment]
https://github.com/rashedsahaji/device_realme_x2.git

yes, I cloned with .git

**Comment by crutchcorn** [comment]
Can you try this again by any chance? I managed to fork the repo, make a commit, and push no problem, so I'm not entirely sure what's going on here

**Comment by tamuseanmiller** [comment]
I honestly thought this was already super known until I just now saw it. I've never been able to push or pull after cloning. I might grab an emulator and test on it later on, might be my phone. 

Just get the regular 404 error on any push or pulls.

Pixel 4XL Android 11 Beta

**Comment by crutchcorn** [comment]
I've fixed this issue when it comes to `pull` in c88970359f42206e81abc5c9856fdcfaee6003a6. The issue with `push`, however, is that you have not logged into a GitHub account and because of this, you're likely getting 403 errors (on top of the errant 404 error that it was throwing before. That's now been fixed).

As such, I want to leave this issue open until we have a better UX of "Hey, you are not logged in yet, go do so before pushing", but the next patch release on the play store should at least fix half of this issue for us

**Comment by tamuseanmiller** [comment]
Just to add on to this, I just checked mine and I am logged in but still cannot push. I'll check again after the update, let me know if I can provide you with anything!

**Comment by crutchcorn** [comment]
FWIW I need to do a total rewrite for how we handle Git Push. I'll be tackling that sometime in the next day or two

You're fantastic @tamuseanmiller - I'll be sure to ask you directly to help me test when I've made things a bit more stable

**Comment by tamuseanmiller** [comment]
Of course, love to help man!

**Comment by crutchcorn** [comment]
This should be the final code commit to fix this issue:

4f38e671bd94cd55ebc6b2573eff9fbb791c95e4

I am asking @tamuseanmiller to test this offline before we publish a new release and close this issue
